2021-09-24T12:25:38|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\OBIS_ScopeFoundry\laser_hardware.py", line 35, in connect
    self.laser = LaserDevice(port=self.port.val, debug=self.debug_mode.val)
  File "C:\LabPrograms\Python\OBIS_ScopeFoundry\laser_device.py", line 14, in __init__
    self.ser = ser = serial.Serial(port=self.port, baudrate=921600,
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM6': PermissionError(13, 'Accesso negato.', None, 5)

2021-09-24T12:25:38|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\OBIS_ScopeFoundry\laser_hardware.py", line 35, in connect
    self.laser = LaserDevice(port=self.port.val, debug=self.debug_mode.val)
  File "C:\LabPrograms\Python\OBIS_ScopeFoundry\laser_device.py", line 14, in __init__
    self.ser = ser = serial.Serial(port=self.port, baudrate=921600,
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': PermissionError(13, 'Accesso negato.', None, 5)

2021-09-24T14:11:02|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\LabPrograms\Python\PROCHIP_Microscope\PROCHIP_Measurement_hexSIM.py", line 178, in run
    self.start_triggered_Acquisition(freq1)
  File "C:\LabPrograms\Python\PROCHIP_Microscope\PROCHIP_Measurement_hexSIM.py", line 486, in start_triggered_Acquisition
    self.start_triggers(freq1)
  File "C:\LabPrograms\Python\PROCHIP_Microscope\PROCHIP_Measurement_hexSIM.py", line 499, in start_triggers
    self.start_triggered_multipleAO_task([self.ni_ao_0,self.ni_ao_1],
  File "C:\LabPrograms\Python\PROCHIP_Microscope\PROCHIP_Measurement_hexSIM.py", line 458, in start_triggered_multipleAO_task
    devices[0].start_task()
  File "C:\LabPrograms\Python\NIdaqmx_ScopeFoundry\ni_ao_device.py", line 228, in start_task
    self.task.start()
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\nidaqmx\task.py", line 1026, in start
    check_for_error(error_code)
  File "C:\Users\Admin\anaconda3\envs\scopefoundry\lib\site-packages\nidaqmx\errors.py", line 127, in check_for_error
    raise DaqError(error_buffer.value.decode("utf-8"), error_code)
nidaqmx.errors.DaqError: Non-buffered hardware-timed operations are not supported for this device and Channel Type.
Set the Buffer Size to greater than 0, do not configure Sample Clock timing, or set Sample Timing Type to On Demand.
Task Name: _unnamedTask<2E>

Status Code: -201025

